name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Actualizado a una versión más reciente de Ruby

      - name: Update RubyGems
        run: gem update --system

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll bundler

      - name: Build the site
        run: bundle exec jekyll build -d ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          headers: |
            /:
              Permissions-Policy: interest-cohort=()
